In [1]:
import pandas as pd
import numpy as np

In [2]:
targets = pd.read_pickle("targets_SLO.pkl")
means = targets[0]
sds = targets[1]

df = pd.DataFrame({
    "mean": pd.Series(means),
    "sd": pd.Series(sds)
})

df.index.name = "key"
df = df.reset_index()
df["accuracy"] = np.abs(df["mean"]) / df["sd"]

df

   key      mean        sd     accuracy
0    1 -1.490889  0.000328  4541.687522
1    2 -1.040908  0.000232  4480.380903
2    5 -0.642857  0.000147  4362.509733
3   10 -0.443294  0.000105  4234.980293
4   30 -0.242244  0.000061  3943.162924
5   50 -0.182033  0.000048  3770.426232
6  100 -0.123377  0.000035  3514.138325
7  200 -0.084287  0.000026  3293.019982
8  500 -0.052149  0.000017  3136.149649

In [3]:
import glob
import pandas as pd

combined_df = pd.concat(
    [pd.read_pickle(f) for f in sorted(glob.glob("pickles/*.pkl"))],
    ignore_index=True
)

In [4]:
combined_df.to_pickle("combined_SLO.pkl")

In [6]:
combined_df['D_mult'].value_counts()

D_mult
0.10    384
0.50    384
0.75    384
1.00    384
1.10    384
0.01     96
Name: count, dtype: int64

In [5]:
k = 10
stat = "U"
d_mult = 0.1
B = 2


df_filtered = combined_df[
    (combined_df["k"] == k) &
    (combined_df["stat"] == stat) &
    (combined_df["B"] == B)
]

df_filtered

,k,stat,n,d,D_mult,B,coverage,average length,n_jobs,simul_size
1160,10,U,10,1,0.10,2,0.97750,2.131944,4,800
1161,10,U,10,5,0.50,2,0.98625,2.285413,4,800
1162,10,U,10,8,0.75,2,0.97125,2.143138,4,800
1163,10,U,10,10,1.00,2,0.97875,2.185833,4,800
1164,10,U,10,11,1.10,2,0.98125,2.222383,4,800
1165,10,U,723,72,0.10,2,0.98625,0.255955,4,800
1166,10,U,723,362,0.50,2,0.97625,0.148100,4,800
1167,10,U,723,542,0.75,2,0.96125,0.134940,4,800
1168,10,U,723,723,1.00,2,0.96750,0.123886,4,800
1169,10,U,723,795,1.10,2,0.96375,0.123897,4,800
1170,10,U,1436,144,0.10,2,0.98125,0.182287,4,800
1171,10,U,1436,718,0.50,2,0.96375,0.104765,4,800
1172,10,U,1436,1077,0.75,2,0.97500,0.094583,4,800
1173,10,U,1436,1436,1.00,2,0.97125,0.087522,4,800
1174,10,U,1436,1580,1.10,2,0.96625,0.085768,4,800
1175,10,U,2149,215,0.10,2,0.98000,0.143771,4,800
1176,10,U,2149,1074,0.50,2,0.96125,0.082934,4,800
1177,10,U,2149,1612,0.75,2,0.97875,0.075735,4,800
1178,10,U,2149,2149,1.00,2,0.95125,0.072764,4,800
1179,10,U,2149,2364,1.10,2,0.95625,0.071398,4,800
1180,10,U,2861,286,0.10,2,0.97625,0.128343,4,800
1181,10,U,2861,1430,0.50,2,0.97750,0.073616,4,800
1182,10,U,2861,2146,0.75,2,0.97500,0.067755,4,800
1183,10,U,2861,2861,1.00,2,0.95750,0.063168,4,800
1184,10,U,2861,3147,1.10,2,0.97500,0.061733,4,800
1185,10,U,3574,357,0.10,2,0.98000,0.110598,4,800
1186,10,U,3574,1787,0.50,2,0.96500,0.066732,4,800
1187,10,U,3574,2680,0.75,2,0.96750,0.059595,4,800
1188,10,U,3574,3574,1.00,2,0.96375,0.055010,4,800
1189,10,U,3574,3931,1.10,2,0.97125,0.054923,4,800
1190,10,U,4287,429,0.10,2,0.98750,0.103815,4,800
1191,10,U,4287,2144,0.50,2,0.96750,0.059657,4,800
1192,10,U,4287,3215,0.75,2,0.96875,0.054995,4,800
1193,10,U,4287,4287,1.00,2,0.94500,0.049385,4,800
1194,10,U,4287,4716,1.10,2,0.97375,0.051338,4,800
1195,10,U,5000,500,0.10,2,0.98125,0.096684,4,800
1196,10,U,5000,2500,0.50,2,0.96875,0.055263,4,800
1197,10,U,5000,3750,0.75,2,0.96625,0.050818,4,800
1198,10,U,5000,5000,1.00,2,0.97250,0.048015,4,800
1199,10,U,5000,5500,1.10,2,0.97500,0.045596,4,800