In [2]:
import pandas as pd
import numpy as np

In [15]:
obj1 = pd.read_pickle("targets.pkl")

In [3]:
targets = pd.read_pickle("targets.pkl")
means = targets[0]
sds = targets[1]

df = pd.DataFrame({
    "mean": pd.Series(means),
    "sd": pd.Series(sds)
})

df.index.name = "key"
df = df.reset_index()
df["accuracy"] = np.abs(df["mean"]) / df["sd"]

df

   key          mean        sd  accuracy
0    5  2.987476e-05  0.000125  0.239120
1   10  5.832811e-05  0.000088  0.659842
2   50  3.532021e-05  0.000040  0.893858
3  100  1.637646e-05  0.000028  0.585973
4  300 -3.109022e-06  0.000016  0.192682
5  500  5.517032e-07  0.000013  0.044130

In [4]:
import glob
import pandas as pd

combined_df = pd.concat(
    [pd.read_pickle(f) for f in sorted(glob.glob("pickles/*.pkl"))],
    ignore_index=True
)

In [6]:
k = 50
stat = "U"
d_mult = 0.1
B = 1


df_filtered = combined_df[
    (combined_df["k"] == k) &
    (combined_df["stat"] == stat) &
    (combined_df["B"] == B)
]

df_filtered

,k,stat,n,d,D_mult,B,coverage,average length,n_jobs,simul_size
144,50,U,50,1,0.01,1,0.96000,2.928518,6,800
145,50,U,50,1,0.02,1,0.96000,2.928518,6,800
146,50,U,50,5,0.10,1,0.95125,2.872700,6,800
147,50,U,50,38,0.75,1,0.94875,2.855401,6,800
148,50,U,50,50,1.00,1,0.94000,2.753846,6,800
149,50,U,50,55,1.10,1,0.93750,2.902090,6,800
150,50,U,757,8,0.01,1,0.96500,1.551194,6,800
151,50,U,757,15,0.02,1,0.97000,1.212790,6,800
152,50,U,757,76,0.10,1,0.96000,0.884201,6,800
153,50,U,757,568,0.75,1,0.95375,0.751651,6,800
154,50,U,757,757,1.00,1,0.95875,0.779850,6,800
155,50,U,757,833,1.10,1,0.95000,0.738436,6,800
156,50,U,1464,15,0.01,1,0.97500,1.216298,6,800
157,50,U,1464,29,0.02,1,0.96875,0.946060,6,800
158,50,U,1464,146,0.10,1,0.96250,0.620112,6,800
159,50,U,1464,1098,0.75,1,0.94375,0.531961,6,800
160,50,U,1464,1464,1.00,1,0.94875,0.560223,6,800
161,50,U,1464,1610,1.10,1,0.94000,0.532288,6,800
162,50,U,2171,22,0.01,1,0.96750,0.934010,6,800
163,50,U,2171,43,0.02,1,0.96000,0.768136,6,800
164,50,U,2171,217,0.10,1,0.94250,0.502017,6,800
165,50,U,2171,1628,0.75,1,0.94375,0.429670,6,800
166,50,U,2171,2171,1.00,1,0.95750,0.447295,6,800
167,50,U,2171,2388,1.10,1,0.96000,0.442360,6,800
168,50,U,2879,29,0.01,1,0.96625,0.838530,6,800
169,50,U,2879,58,0.02,1,0.96500,0.638416,6,800
170,50,U,2879,288,0.10,1,0.95625,0.426868,6,800
171,50,U,2879,2159,0.75,1,0.94625,0.411436,6,800
172,50,U,2879,2879,1.00,1,0.95250,0.381187,6,800
173,50,U,2879,3167,1.10,1,0.93625,0.383034,6,800
174,50,U,3586,36,0.01,1,0.96875,0.770726,6,800
175,50,U,3586,72,0.02,1,0.96375,0.586574,6,800
176,50,U,3586,359,0.10,1,0.96250,0.408486,6,800
177,50,U,3586,2690,0.75,1,0.94500,0.344890,6,800
178,50,U,3586,3586,1.00,1,0.94375,0.333520,6,800
179,50,U,3586,3945,1.10,1,0.93250,0.334738,6,800
180,50,U,4293,43,0.01,1,0.96625,0.669449,6,800
181,50,U,4293,86,0.02,1,0.96500,0.532188,6,800
182,50,U,4293,429,0.10,1,0.94750,0.359122,6,800
183,50,U,4293,3220,0.75,1,0.94625,0.321543,6,800
184,50,U,4293,4293,1.00,1,0.95375,0.318625,6,800
185,50,U,4293,4722,1.10,1,0.93750,0.308261,6,800
186,50,U,5000,50,0.01,1,0.96375,0.645774,6,800
187,50,U,5000,100,0.02,1,0.95750,0.499833,6,800
188,50,U,5000,500,0.10,1,0.95000,0.342127,6,800
189,50,U,5000,3750,0.75,1,0.93875,0.302088,6,800
190,50,U,5000,5000,1.00,1,0.94250,0.291867,6,800
191,50,U,5000,5500,1.10,1,0.95250,0.294824,6,800

In [8]:
np.random.SeedSequence(1).spawn(5)

[SeedSequence(
     entropy=1,
     spawn_key=(0,),
 ),
 SeedSequence(
     entropy=1,
     spawn_key=(1,),
 ),
 SeedSequence(
     entropy=1,
     spawn_key=(2,),
 ),
 SeedSequence(
     entropy=1,
     spawn_key=(3,),
 ),
 SeedSequence(
     entropy=1,
     spawn_key=(4,),
 )]

In [10]:
pd.read_pickle("pickles/simulation_36_k500_B5_V_normal_dist_sample_mean.pkl")

,k,stat,n,d,D_mult,B,coverage,average length,n_jobs,simul_size
0,500,V,500,375,0.75,5,0.96625,0.223306,4,800
1,500,V,500,500,1.00,5,0.95750,0.217365,4,800
2,500,V,500,550,1.10,5,0.95750,0.216449,4,800
3,500,V,1143,857,0.75,5,0.95875,0.142413,4,800
4,500,V,1143,1143,1.00,5,0.94750,0.144175,4,800
5,500,V,1143,1257,1.10,5,0.95125,0.144982,4,800
6,500,V,1786,1340,0.75,5,0.95250,0.115141,4,800
7,500,V,1786,1786,1.00,5,0.95000,0.118293,4,800
8,500,V,1786,1965,1.10,5,0.95750,0.115047,4,800
9,500,V,2429,1822,0.75,5,0.93250,0.099151,4,800
10,500,V,2429,2429,1.00,5,0.94875,0.098059,4,800
11,500,V,2429,2672,1.10,5,0.95375,0.098681,4,800
12,500,V,3071,2303,0.75,5,0.94125,0.087268,4,800
13,500,V,3071,3071,1.00,5,0.94125,0.086918,4,800
14,500,V,3071,3378,1.10,5,0.95875,0.089566,4,800
15,500,V,3714,2786,0.75,5,0.94875,0.081257,4,800
16,500,V,3714,3714,1.00,5,0.94500,0.080936,4,800
17,500,V,3714,4085,1.10,5,0.95000,0.079207,4,800
18,500,V,4357,3268,0.75,5,0.95250,0.073823,4,800
19,500,V,4357,4357,1.00,5,0.94750,0.073449,4,800
20,500,V,4357,4793,1.10,5,0.95500,0.073425,4,800
21,500,V,5000,3750,0.75,5,0.94375,0.068310,4,800
22,500,V,5000,5000,1.00,5,0.95625,0.071476,4,800
23,500,V,5000,5500,1.10,5,0.94250,0.070867,4,800

In [11]:
k_seeds = np.random.SeedSequence(1).spawn(5)

In [12]:
k_seeds

[SeedSequence(
     entropy=1,
     spawn_key=(0,),
 ),
 SeedSequence(
     entropy=1,
     spawn_key=(1,),
 ),
 SeedSequence(
     entropy=1,
     spawn_key=(2,),
 ),
 SeedSequence(
     entropy=1,
     spawn_key=(3,),
 ),
 SeedSequence(
     entropy=1,
     spawn_key=(4,),
 )]

In [13]:
k_s = [int(s.generate_state(1)[0]) for s in k_seeds]

k_s

[1641411168, 1454127163, 2749604155, 3056722145, 3734005922]