In [1]:
import pandas as pd
import numpy as np

In [2]:
targets = pd.read_pickle("targets_SLP_norm.pkl")
means = targets[0]
sds = targets[1]

df = pd.DataFrame({
    "mean": pd.Series(means),
    "sd": pd.Series(sds)
})

df.index.name = "key"
df = df.reset_index()
df["accuracy"] = np.abs(df["mean"]) / df["sd"]

df

    key      mean        sd     accuracy
0     1 -1.595513  0.001786   893.492672
1     2 -1.129156  0.001257   898.006274
2     5 -0.714351  0.000787   907.913939
3    10 -0.504988  0.000550   918.558885
4    50 -0.229082  0.000235   976.065105
5   100 -0.164415  0.000160  1029.095850
6   300 -0.100641  0.000083  1205.774863
7   500 -0.082325  0.000060  1368.597995
8  1000 -0.065494  0.000037  1771.578532
9  2000 -0.055886  0.000021  2625.034317

In [3]:
import glob
import pandas as pd

combined_df = pd.concat(
    [pd.read_pickle(f) for f in sorted(glob.glob("pickles/*.pkl"))],
    ignore_index=True
)

In [4]:
combined_df.to_pickle("combined_SLP.pkl")

In [5]:
k = 2
stat = "V"
d_mult = 0.75
B = 2

df_filtered = combined_df[
    (combined_df["k"] == 2) &
    (combined_df["stat"] == stat) &
    (combined_df["D_mult"] <= 0.5) &
    (combined_df["B"] <= 2)
]

df_filtered

,k,stat,n,d,D_mult,B,coverage,average length,n_jobs,simul_size
1440,2,V,2,1,0.01,1,0.62750,36.507907,8,800
1441,2,V,2,1,0.10,1,0.62750,36.507907,8,800
1442,2,V,2,1,0.50,1,0.62750,36.507907,8,800
1446,2,V,716,7,0.01,1,0.98500,24.462624,8,800
1447,2,V,716,72,0.10,1,0.96500,7.882125,8,800
1448,2,V,716,358,0.50,1,0.96875,4.177622,8,800
1452,2,V,1430,14,0.01,1,0.97500,17.066568,8,800
1453,2,V,1430,143,0.10,1,0.97375,5.655232,8,800
1454,2,V,1430,715,0.50,1,0.96625,2.986452,8,800
1458,2,V,2144,21,0.01,1,0.97000,14.349359,8,800
1459,2,V,2144,214,0.10,1,0.96625,4.468093,8,800
1460,2,V,2144,1072,0.50,1,0.95875,2.337544,8,800
1464,2,V,2858,29,0.01,1,0.98125,11.954492,8,800
1465,2,V,2858,286,0.10,1,0.98125,3.759422,8,800
1466,2,V,2858,1429,0.50,1,0.96875,1.990417,8,800
1470,2,V,3572,36,0.01,1,0.98125,11.246352,8,800
1471,2,V,3572,357,0.10,1,0.97500,3.765182,8,800
1472,2,V,3572,1786,0.50,1,0.97000,1.833223,8,800
1476,2,V,4286,43,0.01,1,0.97625,9.875871,8,800
1477,2,V,4286,429,0.10,1,0.98000,3.315503,8,800
1478,2,V,4286,2143,0.50,1,0.94750,1.677076,8,800
1482,2,V,5000,50,0.01,1,0.97500,9.304911,8,800
1483,2,V,5000,500,0.10,1,0.96125,3.087354,8,800
1484,2,V,5000,2500,0.50,1,0.96875,1.591790,8,800
1584,2,V,2,1,0.01,2,0.66375,13.930083,8,800
1585,2,V,2,1,0.10,2,0.66375,13.930083,8,800
1586,2,V,2,1,0.50,2,0.66375,13.930083,8,800
1590,2,V,716,7,0.01,2,0.99375,8.580745,8,800
1591,2,V,716,72,0.10,2,0.98375,2.823517,8,800
1592,2,V,716,358,0.50,2,0.96875,1.522369,8,800
1596,2,V,1430,14,0.01,2,0.98375,6.324524,8,800
1597,2,V,1430,143,0.10,2,0.98500,2.128172,8,800
1598,2,V,1430,715,0.50,2,0.97500,1.106118,8,800
1602,2,V,2144,21,0.01,2,0.98500,5.302898,8,800
1603,2,V,2144,214,0.10,2,0.98125,1.688436,8,800
1604,2,V,2144,1072,0.50,2,0.97000,0.883265,8,800
1608,2,V,2858,29,0.01,2,0.98125,4.232328,8,800
1609,2,V,2858,286,0.10,2,0.98625,1.509581,8,800
1610,2,V,2858,1429,0.50,2,0.97375,0.789503,8,800
1614,2,V,3572,36,0.01,2,0.98625,4.093064,8,800
1615,2,V,3572,357,0.10,2,0.98875,1.304667,8,800
1616,2,V,3572,1786,0.50,2,0.97125,0.683045,8,800
1620,2,V,4286,43,0.01,2,0.98875,3.648143,8,800
1621,2,V,4286,429,0.10,2,0.98000,1.239662,8,800
1622,2,V,4286,2143,0.50,2,0.97375,0.596884,8,800
1626,2,V,5000,50,0.01,2,0.99000,3.353482,8,800
1627,2,V,5000,500,0.10,2,0.97875,1.151056,8,800
1628,2,V,5000,2500,0.50,2,0.97375,0.571799,8,800

In [12]:
df_filtered = combined_df[
    (combined_df["k"] == 50) &
    (combined_df["stat"] == stat) &
    (combined_df["B"] <= 6) &
    (combined_df["n"] == 1464)&
    (combined_df["D_mult"] == 0.5)
]

df_filtered

,k,stat,n,d,D_mult,B,coverage,average length,n_jobs,simul_size
1022,50,V,1464,732,0.5,1,0.95125,1.534708,4,800
2030,50,V,1464,732,0.5,2,0.95000,0.564657,4,800
2126,50,V,1464,732,0.5,5,0.95375,0.369005,4,800

In [15]:
df_filtered = combined_df[
    (combined_df["k"] == 100) &
    (combined_df["stat"] == stat) &
    (combined_df["B"] <= 6) &
    (combined_df["n"] <= 2000)&
    (combined_df["D_mult"] == 0.5)
]

df_filtered

,k,stat,n,d,D_mult,B,coverage,average length,n_jobs,simul_size
2,100,V,100,50,0.5,2,0.92625,2.057592,4,800
8,100,V,800,400,0.5,2,0.94125,0.734536,4,800
14,100,V,1500,750,0.5,2,0.95000,0.527600,4,800
98,100,V,100,50,0.5,5,0.91875,1.379102,4,800
104,100,V,800,400,0.5,5,0.93375,0.477665,4,800
110,100,V,1500,750,0.5,5,0.94875,0.331866,4,800
2210,100,V,100,50,0.5,1,0.93250,5.296145,4,800
2216,100,V,800,400,0.5,1,0.94750,1.941243,4,800
2222,100,V,1500,750,0.5,1,0.95000,1.408329,4,800